stages:
  get_data:
    cmd: python scripts/data.py
    deps:
      - scripts/data.py
    params:
      - index_col
    outs:
      - data/s2_data.csv
  fit_model:
    cmd: python scripts/fit.py
    deps:
      - data/s2_data.csv
      - scripts/fit.py
    params:
      - index_col
      - target_col
    outs:
      - models/yandex_estate_model.pkl
    metrics:
      - metrics/fit_model_metrics.json
  evaluate_model:
    cmd: python scripts/evaluate.py
    deps:
      - models/yandex_estate_model.pkl
      - scripts/evaluate.py
    params:
      - index_col
      - target_col
      - n_splits
      - n_jobs
      - metrics
    outs:
      - cv_results/cv_res_new.json 